"""Collector DB schema

Revision ID: 399ba3c9f951
Revises: None
Create Date: 2014-09-22 13:21:16.708019

"""

# revision identifiers, used by Alembic.
revision = '399ba3c9f951'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_aid', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_aid', 'external_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_log')
    ### end Alembic commands ###
