"""OSWL stats DB structure

Revision ID: 4da2da15ec42
Revises: 558f628a238
Create Date: 2015-01-27 17:41:50.594143

"""

# revision identifiers, used by Alembic.
revision = '4da2da15ec42'
down_revision = '558f628a238'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# resource_type = postgresql.ENUM('vm', 'tenant', 'volume', 'security_group', 'keystone_user', 'flavor', 'cluster_stats', name='oswl_resource_type', create_type=False)
resource_type = sa.Enum('vm', 'tenant', 'volume', 'security_group', 'keystone_user', 'flavor', 'cluster_stats', name='oswl_resource_type')

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # resource_type.create(bind=op.get_bind(), checkfirst=False)


    op.create_table('oswl_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_node_uid', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('update_time', sa.Time(), nullable=False),
    sa.Column('resource_type', resource_type, nullable=False),
    # resource_type = postgresql.ENUM('vm', 'tenant', 'volume', 'security_group', 'keystone_user', 'flavor', 'cluster_stats', name='oswl_resource_type', create_type=False)

    sa.Column('resource_data_added', postgresql.JSON(), nullable=True),
    sa.Column('resource_data_removed', postgresql.JSON(), nullable=True),
    sa.Column('resource_data_modified', postgresql.JSON(), nullable=True),
    sa.Column('resource_data_current', postgresql.JSON(), nullable=True),
    sa.Column('resource_current_checksum', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_node_uid', 'external_id')
    ),
    op.create_index(op.f('ix_oswl_stats_creation_date'), 'oswl_stats', ['creation_date'], unique=False)
    op.create_index(op.f('ix_oswl_stats_external_id'), 'oswl_stats', ['external_id'], unique=False)
    op.create_index(op.f('ix_oswl_stats_master_node_uid'), 'oswl_stats', ['master_node_uid'], unique=False)
    op.create_index(op.f('ix_oswl_stats_resource_type'), 'oswl_stats', ['resource_type'], unique=False)
    # op.alter_column(u'installation_structures', 'structure',
    #            existing_type=postgresql.JSON(),
    #            nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(u'installation_structures', 'structure',
    #            existing_type=postgresql.JSON(),
    #            nullable=False)
    op.drop_index(op.f('ix_oswl_stats_resource_type'), table_name='oswl_stats')
    op.drop_index(op.f('ix_oswl_stats_master_node_uid'), table_name='oswl_stats')
    op.drop_index(op.f('ix_oswl_stats_external_id'), table_name='oswl_stats')
    op.drop_index(op.f('ix_oswl_stats_creation_date'), table_name='oswl_stats')
    op.drop_table('oswl_stats')
    # op.drop_type('oswl_resource_type')
    resource_type.drop(bind=op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
