"""Initial migration

Revision ID: 4dc5d9c6c16e
Revises: None
Create Date: 2014-09-19 18:58:38.430430

"""

# revision identifiers, used by Alembic.
revision = '4dc5d9c6c16e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_aid', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_log')
    ### end Alembic commands ###
