"""Collector DB schema

Revision ID: 558f628a238
Revises: None
Create Date: 2014-09-22 15:20:31.405870

"""

# revision identifiers, used by Alembic.
revision = '558f628a238'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_aid', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_aid', 'external_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    ### end Alembic commands ###
